### PR TITLE
[Enhancement] REST Api: Location

### PR DESCRIPTION
**Pull request by brettgus**
## Description
Very simple modification that allows querying of and modifying location using a URL.  

Being able to change your location is pretty important since our location changes frequently when we're chasing down pokemon.  

One use case that I have currently have is that I'm using pyicloud to pull my iphone's location (using the built in "find my iphone" functionality) and then having that update PokeAlarm.

This will output the current location setting as lat,lon coordinates:
http://IP_ADDRESS:PORT/location/

To change the location,
http://IP_ADDRESS:PORT/location/41.72,-81.53

## How Has This Been Tested?
Tested on my Ubuntu 16.04 machine
This only makes a small modification to flask in runwebhook.py

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Wiki Update

Will update wiki if this gets merged, using examples such as in the PR description

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by cheezy64** [comment]
Really cool idea!  +1

**Comment by brettgus** [comment]
@kvangent I know you mentioned you wanted this to be more restful.  Would you want it to look like this?

**GET /location/ - Get current location setting**
_Response_
Response Type: application/json
{
&nbsp;&nbsp;&nbsp;&nbsp;locationSet (boolean),
&nbsp;&nbsp;&nbsp;&nbsp;latitude (float, optional),
&nbsp;&nbsp;&nbsp;&nbsp;longitude (float, optional)
}

**POST /location/ - Set location** 
_Request_ 
Type: application/json
Parameters:
{
&nbsp;&nbsp;&nbsp;&nbsp;latitude (float),
&nbsp;&nbsp;&nbsp;&nbsp;longitude (float)
}

_Response_
Type: application/json 
{
&nbsp;&nbsp;&nbsp;&nbsp;locationChanged (boolean),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;latitude (float),
&nbsp;&nbsp;&nbsp;&nbsp;longitude (float)
}

**Comment by kvangent** [comment]
Implemented in 564599d8aa8311e738125c11a8f0ea8f75b22634.

**Comment by joberembt** [comment]
@brettgus I'd like more info about your pyicloud integration...

**Comment by brettgus** [comment]
@joberembt you'd have to rework it so it works with post and not get like the current code:

```
        api = PyiCloudService('<EMAIL HERE>', '<PASSWORD HERE>')
        loc = api.devices['<DEVICE ID HERE>'].location()
        horiz = loc.get("horizontalAccuracy")
        lat = loc.get("latitude")
        lon = loc.get("longitude")
        url = "http://localhost:<PORT>/location/%s,%s" % (str(lat), str(lon))
        address = get_address(lat,lon)
        if (horiz < 100):
                resp = requests.get(url)
```

**Comment by joberembt** [comment]
Are you using this solely for repositioning the alarm or do you have your map scan follow you too?

**Comment by brettgus** [comment]
@joberembt Just using it for repositioning the alarm.  However, [iPokeGo](https://github.com/istornz/iPokeGo) is another good solution if you're looking for something that follows you.

**Comment by Imoq** [comment]
This is exactly what I was looking for! Will try to pull this PR tomorrow, any reason why it isn't on the main branch yet? Thanks!

**Comment by Bart274** [comment]
I need to try this immediately :)
@brettgus & @joberembt : I'm running home-assistant.io on my server, I use pyicloud to track the location of my device and it automatically updates the location of my map when I have moved more than 200m. It works really well and I have it set up so it would also allow myself to arm and disarm my alarm because of it :)

**Comment by brettgus** [comment]
@Imoq It was integrated in 564599d.  We don't have it documented yet, the syntax is slightly different then in this PR though.

```
POST /location/  - updates location
   'location' is a lat,lon pair or an address

GET /location/  - returns location

GET /geofence/ - returns a map of current location and geofence
```

**Pull request closed without merging**
