### PR TITLE
Updated magikarp/gyrados, 2nd gen pokemons & gyms icons

### PR DESCRIPTION
**Pull request by MARTINI1**
## Description

I long ago noticed that the icons of the gyms were horrible and now with the beta of v3.2 I have decided to renew the icons, apart from changing the images of the 2nd gen to sprites of Pokemon Go as the 1st gen.

## How Has This Been Tested?

In my own pokealarm with branch 3.2.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tallypokemap** [comment]
New sprites are awesome.  The gym icons are okay.  I think the gym icons were chosen to mimic the icons in RM.  I think RM has migrated to the shield logos being the default.  The shield logos are much better than the current logos.  I recommend using them.  Example:

https://raw.githubusercontent.com/RocketMap/RocketMap/develop/static/forts/Valor.png

**Comment by MARTINI1** [comment]
So I had them when I was about to do an old pr but before doing this PR I started looking for images of icons of gims and I loved these I have put here

I like the style more and it is more hidden to one side than not an icon as a shield xD

These gym sprites I have taken from the images of the unity motor of the game, are the team icons that come out behind the trainer when entering the profile

**Comment by kvangent** [comment]
@MARTINI1 Can I get you to PM me on discord when you are around to discuss these?

**Comment by MARTINI1** [comment]
@kvangent I have already put the sizes of the babies sprites correctly as we have commented in discord and hope that now everything be fine

**Pull request merged**
