### PR TITLE
Send alerts in a different thread

### LINKED ISSUE #8: Broken Pipe (Errno 32)
After running the alarm for a bit , and after receiving about 3 notification for pokemon, the following error message is displayed. 

2016-07-29 23:09:12,703 [ alarm_manager] [   INFO] Horsea notication was triggered!
2016-07-29 23:09:12,731 [connectionpool] [   INFO] Resetting dropped connection: api.pushbullet.com
2016-07-29 23:09:13,864 [connectionpool] [  DEBUG] "POST /v2/pushes HTTP/1.1" 200 None
Traceback (most recent call last):
  File "runwebhook.py", line 45, in <module>
    app.run(debug=config['DEBUG'],host=config['HOST'], port=config['PORT'])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/werkzeug/serving.py", line 694, in run_simple
    inner()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/werkzeug/serving.py", line 659, in inner
    srv.serve_forever()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/werkzeug/serving.py", line 499, in serve_forever
    HTTPServer.serve_forever(self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 233, in serve_forever
    self._handle_request_noblock()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 292, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
socket.error: [Errno 32] Broken pipe

I don't have any idea what might cause this or where to even start to attempt to find a fix.

### PR DESCRIPTION
**Pull request by wbowling**
The webhook request could time out waiting for the notifications to be sent. This should fix #8.

### CODE REVIEW

**Comment by dmtdabs** [comment]
I attempted to implement your fix by changing the lines runwebhook.py, but after the scan runs for a while, i am still getting the same error.

2016-07-30 10:34:16,672 [ alarm_manager] [   INFO] Horsea notication was triggered!
2016-07-30 10:34:16,739 [connectionpool] [   INFO] Resetting dropped connection: api.pushbullet.com
2016-07-30 10:34:21,783 [connectionpool] [  DEBUG] "POST /v2/pushes HTTP/1.1" 200 None
Traceback (most recent call last):
  File "runwebhook.py", line 45, in <module>
    app.run(debug=config['DEBUG'],host=config['HOST'], port=config['PORT'])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/werkzeug/serving.py", line 694, in run_simple
    inner()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/werkzeug/serving.py", line 659, in inner
    srv.serve_forever()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/werkzeug/serving.py", line 499, in serve_forever
    HTTPServer.serve_forever(self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 233, in serve_forever
    self._handle_request_noblock()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 292, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
socket.error: [Errno 32] Broken pipe

**Comment by kimifoud** [comment]
This PR has fixed the _[Errno 32] Broken pipe_ problem for me.

**Comment by kvangent** [comment]
This isn't actually fixing the problem, it is just reducing the change of it happening. The problem is the Map closes the socket very quickly, and so when Flask tries to reply the OS has already closed the socket. This may be worth doing to reduce the Map's wait time, but Locks on the alarm object will need to be introduced.

**Comment by wbowling** [comment]
It is currently waiting for all of the alarms to be triggered before replying, and as they involve external services there is no way of knowing how long they count take. Even bumping the Map timeout to 10 seconds the problem could still occur.

One you have recieved the data from the Map you should return success and then process it later, there is probably a better was of doing it than this PR but I've been running it for 24h and no issues.

**Comment by kvangent** [comment]
@wbowling I agree with you that adding another thread is going to reduce this, but it took about 5 minutes with 3 maps feeding into it to run into the problem with the timeout set to one. Also I had an occasion where I was notified of the same pokemon. But your idea is solid.

I think a more elegant solution would be spinning off a separate thread and use a list to transfer the information over. The second thread can then pop off the Pokemon one at a time to deal with them. My understanding is that appending it lists is atomic, so I think that would avoid any issues without introducing a lock.

**Pull request closed without merging**
