### PR TITLE
Add color to discord embeds

### PR DESCRIPTION
**Pull request by tallypokemap**
## Description
Adds color to discord embeds based on IV (in the case of pokemon), team (in the case of gym), or simply if it is a lured pokestop.  Examples in screenshot

## How Has This Been Tested?
I've been using this set up for months without flaw

## Screenshots (if appropriate):
[Screenshot of pokemon example](http://imgur.com/cvcvWjw)
[Screenshot of gym example](http://imgur.com/sN62LWR)
[Screenshot of lure example](http://imgur.com/XWPkT22)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tallypokemap** [comment]
This pr hard codes the colors and values which is why I assume it hasn't been looked at much.  I've come up with an idea to fix that and will comment again when I have updated.

**Comment by MARTINI1** [comment]
Nice pr, quiet if nobody comments, I think it is because it is simple that it is not necessary to comment much, besides that you have done a great job 👍 

For my part, I'm close to being able to test it, I still have no account at 30 but almost, 29 xD
although I tried your old version when you passed it by discord, only with pokes and was very good

As something extra that could be done, is that in the config you can customize only the colors of the iv pokes, the color of baits and gims I do not think anyone wants to change them

What you think, because apart from this I do not think you can do more things

**Comment by tallypokemap** [comment]
I was thinking something exactly like that but in the alarms file.  Something like:
```
"color": {
    "iv_color_breakpoints": [iv1, iv1,...]
    "iv_color": [color1, color2, ....]
    "lure_color": color
}
```

**Comment by MARTINI1** [comment]
Good idea, I was thinking about only of the colors, but not in modifying ranges of ivs, how would they be? "Iv_color_breakpoints": [0-20,21-40, ...] or how?

It would be nice to make an option of just modifying colors and that already makes by default the range that you have already done, and then as plus be able to modify the type ranges with the iv_color_breakpoints option

The color of baits in pink as it is in the original game I think it's OK xD

**Comment by dongemus** [comment]
Just wanted to say I appreciate what you are doing here, This will be very handy

**Comment by MARTINI1** [comment]
Missing color assignment for level 5 raid

I would put something purple to match with the color style of the egg

And good job keeping this updated 👍

**Comment by MARTINI1** [comment]
@tallypokemap this is the raid egg 5 in case you have not seen it

https://github.com/fosJoddie/PokeAlarm/blob/032aa1ba30b0f0b93d5b8ce1bcfeaeb151aded0a/icons/egg_5.png

Would put a purple like this: http://www.color-hex.com/color/b55df1

The other colors would put one like the color of egg that has but one dark and one clear but they are not bad the chosen ones

It will be shortly the use this level of raids because day 12 niantic already announced "unique and powerful Raid Bosses", more clear impossible xD 

And now looking at the code I do not see in the sections of raid or egg "color" as if it is in pokemon and gym as for example for discord, is it implemented in another way or is it that you have forgotten?

**Comment by MARTINI1** [comment]
Oh, you still with this PR @tallypokemap ?

I am glad that you continue it although kvangent closed it, to see if you give a final polish with the last changes and finally merge

Good choice of raids level 5 color 👍

**Comment by tallypokemap** [comment]
Oh yea, I'm still with it.  It's kind of a hack job.  If someone has a better implementation or if @kvangent has a suggestion, I'm willing to go with it.

**Pull request closed without merging**
