### PR TITLE
Added Dockerfile

### PR DESCRIPTION
**Pull request by annessi**
Added a basic Dockerfile to run PokeAlarm inside a docker. 
PokemonGo-Map needs to be running inside another docker.

## How Has This Been Tested?
Tested on Synology

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kvangent** [comment]
So the reason I'm leaving this open is because I'm going to switch all the Alarms over to self-contained modules that lazy import - They won't import the needed external modules (like Slacker or Twitter) until they are actually created and if not installed will install via pip. This will most likely not work with this docker.

If you can test and confirm that this is not the case, or create a suitable workaround I'll be glad to accept this.

**Comment by annessi** [comment]
As soon as you switch I'll test the dockerfile.

**Comment by kvangent** [comment]
@annessi I've switched the remaining packages over.

**Comment by annessi** [comment]
I've tested the Dockerfile and it's working just fine also with the modules.

screen shot 2016-08-18 at 08 46 23

**Pull request merged**
