### PR TITLE
fix duplicate notification

### PR DESCRIPTION
**Pull request by blaulan**
use 'encounter_id' instead of 'id' to avoid duplicate notification.

### CODE REVIEW

**Comment by kvangent** [comment]
I like the changes on Slack. Are the icons we are using up in Public Domain though? I want to make sure we aren't pulling bandwidth from someone else.

**Comment by kvangent** [comment]
We can use the ones in PokemonGo-Map if we can find a reasonable host. 

Would you please rebase for me as well?

**Comment by reactortrip** [comment]
I used your other alarm til the Niantic blockade and switched to a modified version of the dev with your code to add the alarm back in.  I edited my slack alarm to include emoji support by adding in ":pokemon-" + Pokemon name + ":".  So using icons isn't necessary, you can just have people add the custom emojis from this page to their slack.  Won't fix other services though.

https://github.com/Templarian/slack-emoji-pokemon

**Comment by reactortrip** [comment]
Pic of my alarms in slack

http://i68.tinypic.com/mazalg.jpg

**Comment by kvangent** [comment]
@reactortrip If you would like to make a tutorial for how to do that, I can include it in the wiki.

**Comment by blaulan** [comment]
I've modified the code to use @reactortrip 's method for pokemon image.

**Comment by kvangent** [comment]
@blaulan Will they still need to add their own icons?

**Comment by blaulan** [comment]
@kvangent Yes, the instructions can be found from https://github.com/lambtron/emojipacks. However, I'm still trying to find a high solution pokemon icon pack. Those from PokemonGo-Map are in a single image, which can't be passed to Slack.

**Comment by kvangent** [comment]
@blaulan What about the ones in static/icons?

**Comment by blaulan** [comment]
@kvangent we can use those for now, although their resolution is low. I will include them in the next commit.

**Comment by kvangent** [comment]
Looks good, thanks for this.

**Pull request merged**
