### PR TITLE
Iv alerts

### PR DESCRIPTION
**Pull request by abirmingham**
## Description

Fixed a bug where Pokemon moves were always shown as "None" in notifications.
Fixed a bug where notifications failed due to a KeyError.

## How Has This Been Tested?

Ran this on my local machine. Tested using MangoScango/PokemonGo-Map on branch "IVs-and-Moves" (current commit be16e9ba)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kvangent** [comment]
I believe that both of these issues should be fixed already. If you continue to have problems please let me know.

**Comment by abirmingham** [comment]
@kvangent thanks!

Your commits look good except for one question about 0ac9516e at alarm_manager:217 -
```
@@ -219,12 +219,12 @@ class Alarm_Manager(Thread):
                        '12h_time': timestamps[1],
                        '24h_time': timestamps[2],
                        'dir': get_dir(lat,lng),
-                   'move1': move1,
-                   'move2': move2,
+                 'move1': str(move1),
+                 'move2': str(move2),
                        'atk': atk,
-                   'dfs': dfs,
+                 'def': dfs,
                        'sta': sta,
-                   'iv': iv
+                 'iv': "%.2f" % iv
                }
```

Did you mean to change dfs->def? I must admit def is more intuitive.

**Comment by kvangent** [comment]
Yes, I did. dfs make me think of depth first search. I had to leave dfs for the variable name since def is a reserved word.

**Comment by abirmingham** [comment]
@kvangent thanks!

**Pull request closed without merging**
