### PR TITLE
Add Discord support via webhooks

### PR DESCRIPTION
**Pull request by twoopi**
## Description
Added Discord support through webhooks. 
Just create a webhook for the channel you want to use, and use the webhook URL for the api_key.
Most of the code was just copied from the Slack script, just modified for webhooks in the form used by Discord. I'm not a python guy, so feel free to complain about my bad coding. But it works.

## How Has This Been Tested?
Yep. Currently using it to slowly migrate my community from Slack to Discord.
Been running without errors overnight. Compared notifications from Slack to Discord, all exactly the same.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by radzuky** [comment]
Working good so far.

**Comment by kvangent** [comment]
I'm fine with pulling this if I can get a few more users to verify it is working well.

**Comment by reme-dy** [comment]
I'll give it a shot once my home internet is back up and running.

**Comment by radzuky** [comment]
Is the map part of slack working with this. I added "map"  but it doesn't show.

**Comment by kvangent** [comment]
@radzuky This is for Discord, not Slack. 

@twoopi You will need to make a wiki page and submit it to https://github.com/kvangent/PokeAlarmWiki as well.

**Comment by radzuky** [comment]
@kvangent right, thought maybe it would show since it's based on Slack.

**Comment by twoopi** [comment]
I didn't bother with the map support, I never used it in the Slack alarms.

Although you can have multiple embeds per webhook, so you could easily attach an image URL for it to show at the bottom of a post.

Added the PR to the wiki, thanks for the link.

**Comment by twoopi** [comment]
Added the code for map support.

**Comment by Bart274** [comment]
I'll try it later today or tomorrow and will report back ;)

**Comment by Bart274** [comment]
@kvangent I can confirm this works great :-)

**Comment by Bart274** [comment]
@twoopi is it possible to add a second message with just the coordinates of the pokemon?

**Pull request merged**
