### PR TITLE
[Enhancement] Add switch to disable first tweet at initialization

### PR DESCRIPTION
**Pull request by Becold**
## Description
Add optional setting `startup_message` for Twitter module.
Default on "True".
If set to "False", it prevent the Alarm from tweeting "PokeAlarm has intialized!" at startup

## How Has This Been Tested?
With my twitter, 2 times and it work.

## Screenshots (if appropriate):
image

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Wiki Update
Add to the optionnal options something like : 
```
`startup_message` | `Trigger a tweet at initialization` | `True`
```
## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Becold** [comment]
Wait. Dont merge it.
It broke

**Comment by gkuiper** [comment]
Wouldn't it be better to make this a global option? So also disable the initial message for the other services?

**Comment by kvangent** [comment]
@gkuiper I can add this feature in to the rest of the alarms if there is interest. 

@Becold There is a parse Boolean function in the utils designed to interpret a number of things as True. You should make use of it here. 

I also think that you should change the name of the parameter to 'startup_message'.

**Comment by kvangent** [comment]
One more thing that I just noticed that that you have the time as `utcnow()` instead of just `now()`. This will reintroduce the incorrect timezone you wanted changed before as well.

**Pull request merged**
