### PR TITLE
Added travel time to Pokemon

### PR DESCRIPTION
**Pull request by brettgus**
## Description
Allows for addition of &lt;walking_time&gt; and &lt;driving_time&gt; variables when location is set.  Will estimate walking/driving time to reach pokemon. 

## How Has This Been Tested?
Tested with multiple different locations and several edge cases (between multiple continents).
Ran on Ubuntu 16.04 with python 2.7
However, 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by fgnn** [comment]
Thanks for adding this. Cleaner than my implementation in #113. Some code from both can probably be merged.


Missing features compared to #113 are 1) a go-nogo icon being available based on walking distance,  2) bearing and compass direction arrows, 3) API key added (although we should never get to 2500 notifications per day, a dev may though. It should probably be added as optional)

**Comment by brettgus** [comment]
Why add the API key option though? If google doesn't require it, I don't see why you'd need to add it.  Why count usage against your API key if you don't need to?  

The only reason to add it would be if we needed to get transit directions, as then it is required.... so I guess that could be a compelling reason.  Although is anyone using transit to catch pokemon?  I would think the amount of wait time required (for the train/bus) would not make it worth doing.

And yeah, agreed, there's definitely stuff that can be merged at first glance.  I'm usually driving, so compass direction wasn't even a thought to me, but that could definitely be helpful.  Also, checking whether you'll make it there before expire time is helpful.

**Comment by brettgus** [comment]
Ahh @mrchops1024 just mentioned this in the other PR... that they throttle you for a little while if you request too too frequently without an API key.

**Comment by brettgus** [comment]
@kvangent If there's interest in pulling this into the project, I could integrate elements of @fgnn's code in #113 into this.

If so, would also like to hear your opinion on whether the API key should be added.

**Comment by kvangent** [comment]
@brettgus Not that there is not interest, I just had a long weekend and am in the process of getting things caught back up. I need some time to look them over and figure out differences before I decide.

**Comment by kvangent** [comment]
Close because in need of a rebase. Hoping to implement with google api rework.

**Pull request closed without merging**
