### PR TITLE
Enable pure cardinal directions (N, S, E, W) in addition to NE/NW/SE/SW.

### PR DESCRIPTION
**Pull request by snooter**
## Description
The DIR expansion currently only shows NE/NW/SE/SW, and never pure cardinal directions (N, S, E, W). This enables all 8 possible directions.

## How Has This Been Tested?
Tested in real-life Twitter feed.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kvangent** [comment]
What is the intent of the extra 90 degrees added in?

**Comment by snooter** [comment]
It's part of the algorithm - when you add that, then floor the division by 45, it dumps it in the correct bucket. There might be a way to do it without that, but I know this one works.

**Comment by dripdropper** [comment]
I can confirm that this algorithm appears to be functionally equivalent to the code that I posted in issue #331.  Since mine was independently written, the algorithm is almost surely correct.

This code could be clearer if it were written in two parts.  The first part would calculate the bearing angle, and the second part would translate the angle into a direction string ("N", "NE", etc.).  The extra 90 degrees and round() stuff are used for the second part to map the angle to the directions array.

**Comment by kvangent** [comment]
I guess I would prefer if we can at least source the algorithm we are using since it is fairly complex. From my understanding it should give the degrees from north, so the quarter turn is not really making any sense to me. 

I'll tested it out today to see if I'm wrong.

**Comment by dripdropper** [comment]
Looking more closely at the code, this algorithm appears to have the y and x parameters of atan2() swapped, which would explain why it doesn't start from north and why there are extra manipulations needed to get the correct direction.

Are you looking for an open source library with the algorithm, or just some references to show it is correct?

**Comment by kvangent** [comment]
Preferably some references to ensure it is correct.  I have a feeling it's not going to work the way I think it is going to work, but I haven't gotten to testing it yet.

**Comment by dripdropper** [comment]
Here are the references I based my algorithm on:
http://stackoverflow.com/questions/3209899/determine-compass-direction-from-one-lat-lon-to-the-other
https://www.dougv.com/2009/07/calculating-the-bearing-and-compass-rose-direction-between-two-latitude-longitude-coordinates-in-php/
http://stackoverflow.com/questions/1971585/mapping-math-and-javascript
http://www.martinhansen.no/posts/20110414-getting-the-bearingheading-betweet-2-coordinates

I verified that snooter's algorithm had the same results for 100 different points I generated.

**Comment by kvangent** [comment]
It seems to be correct compared to traditional equations and my own testing, I'm just concerned that I don't understand it enough and if there is a problem with in 3 months from now with it I'll be unable to diagnose it.

Give me a another day or two to see if I can find some time to sit and break it down  a bit more. It's nothing against it or you, I just want to make sure I have a little more understanding of it before I assume responsibility of it. Sorry for the wait.

**Pull request merged**
